services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: ad-chatbot-mvp-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-storage:/qdrant/storage

volumes:
  qdrant-storage:
